name: Daily workflow to parse all Microsoft Sentinel and Microsoft Security Services Built-in Alerts to csv file

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 AM (UTC) everyday 

jobs:
  download-mitreattackmap:
    name: Daily workflow to parse all Microsoft Sentinel and Microsoft Security Services Built-in Alerts to csv file
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Checkout the repo
        uses: actions/checkout@v3
        with:
          path: master
          fetch-depth: 0

      - name: 🐍 Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8" 
          architecture: "x64" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas attackcti pyyaml requests_html

      - name: 🚀 Run automation script
        run: python master/.script/public-feeds/mitre-attackmap.py

      - name: Commit files
        run: |
          cd master
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add 'Sample Data/PublicFeeds/MITREATT&CK/MicrosoftSentinel.csv'
          git commit -m "Adding updated MITRE Attackmap files" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: "master"